package com.cisco.iask.entity;

import com.google.api.client.util.DateTime;
import lombok.Data;

import javax.persistence.*;

/**
 * Created by sarthiya on 21/04/16.
 */
@Data
@Entity(name = "questions")
@Table(name = "questions")
@NamedQueries(value = {
        @NamedQuery(name = "com.cisco.iask.entity.Question.findbyUserName",
                query = "select e from questions e where e.username = :name "),
        @NamedQuery(name = "com.cisco.iask.entity.Question.findAllQuestions",
                query = "select e from questions e"),
        @NamedQuery(name = "com.cisco.iask.entity.Question.searchbyText",
                query = "select e from questions e where e.title like :title")
})
public class Question {

    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * employee first name.
     */
    @Column(name = "title")
    private String title;
    /**
     * employee last name.
     */
    @Column(name = "description")
    private String description;
    /**
     * employee username.
     */
    @Column(name = "username")
    private String username;

    /**
     * employee username.
     */
    @Column(name = "answers")
    private long answers;

    /**
     * employee e-mail.
     */
    @Column(name = "dtime")
    private DateTime dateTime;
    /**
     * A no-argument constructor.
     */
    public Question() {
    }
    /**
     * A constructor to create employees. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Question(String title, String description, String username,
                    long answers, DateTime dateTime) {
        this.title = title;
        this.description = description;
        this.username = username;
        this.answers = answers;
        this.dateTime = dateTime;
    }

}
