package com.cisco.iask.entity;

import lombok.Data;

import javax.persistence.*;

/**
 * Created by sarthiya on 21/04/16.
 */
@Data
@Entity(name = "users")
@Table(name = "users")
@NamedQueries(value = {
        @NamedQuery(name = "com.cisco.iask.entity.User.findbyUsername",
                query = "select e from users e where e.username = :name ")
})
public class User {

    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * employee first name.
     */
    @Column(name = "first_name")
    private String firstName;
    /**
     * employee last name.
     */
    @Column(name = "last_name")
    private String lastName;
    /**
     * employee username.
     */
    @Column(name = "username")
    private String username;

    /**
     * employee username.
     */
    @Column(name = "password")
    private String password;

    /**
     * employee e-mail.
     */
    @Column
    private String e_mail;
    /**
     * A no-argument constructor.
     */
    public User() {
    }
    /**
     * A constructor to create employees. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public User(String firstName, String lastName, String username,  String e_mail,
                String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.e_mail = e_mail;
        this.password = password;
    }

}
