databaseConfiguration:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: password

  # the JDBC URL
  url: jdbc:mysql://localhost/iask

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 30s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 500

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 10s

jerseyClientConfiguration:
  timeout: 120000ms
  connectionTimeout: 500ms
  timeToLive: 1 hour
  cookiesEnabled: true
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0s
  minThreads: 1
  maxThreads: 128
  gzipEnabled: false
  gzipEnabledForRequests: false

http:
  port: 8073
  adminPort: 8173